### ISSUE TITLE
Sian Lewis Draft Résumé

### ISSUE THREAD

**Issue by allsian** [ga-students/d.c.-outcomes-homework#7]
[Sian Lewis - Lead Data Scientist.pdf](https://github.com/ga-students/d.c.-outcomes-homework/files/1703801/Sian.Lewis.-.Lead.Data.Scientist.pdf)

**Comment by allysonaustin** [comment]
Hi Sian,

Thanks for submitting your resume! I have few comments for you below. Let me know if you have any questions about my comments.

1. I understand that you had not completed your brand statements before these submissions. Once you've completed your brand statement, use it to take place of the summary you have listed here.

2. Keep the focus of your DSI section on you, and not on the course. YOU analyze data & convey facts and YOU predict what happens next. Instead of repeating the skills in a similar pattern to your skills section, list your projects from the course, and include the skills you used to complete each one. 

3. Your resume should be one page for 10 years of experience; you'll need to pare down to meet this standard. Your styling has a lot of white space, but you will certainly need to pare back. Many of the earlier entries follow a very repetitive format and it may be useful omit some of this information.

4. It seems that you've made paragraph entries into bulleted lists; there are several bullets that end with commas or the word "and".

5. A few stylistic comments:
- Line up our margins/justifications so they're consistent across sections. Their current arrangement can feel a bit haphazard.
- Be sure that your colors are dark enough to be readable. I find it easiest to determine this with printed copies.
- Some of your bullet points have periods at the end, and some don't. Be sure to keep your formatting consistent.

Great work! Let me know if you have questions.
A

**Comment by allsian** [comment]
Allyson, 
Thank you so very much for the feedback. I have followed your excellent directions. My resume is now down to one page, formatted, and aligned. My new brand statement is incorporated. Please let me know if you have further feedback. Again, many thanks.
[Sian Lewis - Your Data Scientist.pdf](https://github.com/ga-students/d.c.-outcomes-homework/files/1738980/Sian.Lewis.-.Your.Data.Scientist.pdf)
