### ISSUE TITLE
Zaheer Resume Draft

### ISSUE THREAD

**Issue by zrangwala1981** [ga-students/d.c.-outcomes-homework#8]
[Zaheer Rangwala GA_RESUME.docx](https://github.com/ga-students/d.c.-outcomes-homework/files/1699317/Zaheer.Rangwala.GA_RESUME.docx)

**Comment by allysonaustin** [comment]
Hi Zaheer,

Thanks for submitting your resume! I have few comments for you below. Let me know if you have any questions about my comments.

1. Be sure to include your contact information (email/phone) and a link to your portfolio right at the top near your name.

2. There is no need for additional description of DSI in your education section. Instead, move this description to the first entry under Experience and leave it as a line-item only. As you complete the course, add your projects to the DSI section. Focus on describing the project through the skills you employed to create each one.

3. Your resume should be one page - edit down to meet this standard. You may it helpful to edit both content, as well as make adjustments to your styling to give yourself sufficent room to build up your data experience.

4. A few stylistic notes:
- Your skills section is awkwardly placed and the spacing is different from the rest of the resume. Find a way to better integrate it into the resume so that it feels like it belongs visually, and that the content is featured in an appealing way.
- Each of your skills sections is formatted in a different way. Keep your font, sizing, and style consistent across entries to improve readability.
- Put spaces on either side of the dashes between dates (2015 - 2018).

Great work! Let me know if you have questions.
A
